In [2]:
import requests, pandas, os, re, itertools,numpy
api_key ="605ccbb87ba11af806764361c2debc27dea1915a"

In [4]:
acs_tables_key=pandas.read_excel("C:\\Users\\Umamounika.Karukonda\\OneDrive - Fractal Analytics Pvt. Ltd\\Documents\\Hill's\\US Vet Consulting\\Codes\\ACS2017_Table_Shells_edited.xlsx",sheet_name="Sheet1")

In [5]:
actual_acs_tables_key=pandas.read_excel("\\\\172.16.10.43\\Hills US Vet Channel Consulting (18-SCP-2568)\\Phase 2 - Suggested Order\\Demographics\\US Demographics\\Codes for Census.gov\\ACS2017_Table_Shells.xlsx")
acs_tables_key.dropna(how="all")
acs_tables_key.dropna(axis=1,how="all")

,Table ID,Line,UniqueID,Stub
0,B00001,1.0,B00001_001,Total - UNWEIGHTED SAMPLE COUNT OF THE POPULA...
1,B00002,1.0,B00002_001,Total - UNWEIGHTED SAMPLE HOUSING UNITS
2,B01001,2.0,B01001_002,Total Male population
3,B01001,3.0,B01001_003,Male Under 5 years
4,B01001,4.0,B01001_004,Male 5 to 9 years
5,B01001,5.0,B01001_005,Male 10 to 14 years
6,B01001,6.0,B01001_006,Male 15 to 17 years
7,B01001,7.0,B01001_007,Male 18 and 19 years
8,B01001,8.0,B01001_008,Male 20 years
9,B01001,9.0,B01001_009,Male 21 years
10,B01001,10.0,B01001_010,Male 22 to 24 years
11,B01001,11.0,B01001_011,Male 25 to 29 years
12,B01001,12.0,B01001_012,Male 30 to 34 years
13,B01001,13.0,B01001_013,Male 35 to 39 years
14,B01001,14.0,B01001_014,Male 40 to 44 years
15,B01001,15.0,B01001_015,Male 45 to 49 years
16,B01001,16.0,B01001_016,Male 50 to 54 years
17,B01001,17.0,B01001_017,Male 55 to 59 years
18,B01001,18.0,B01001_018,Male 60 and 61 years
19,B01001,19.0,B01001_019,Male 62 to 64 years
20,B01001,20.0,B01001_020,Male 65 and 66 years
21,B01001,21.0,B01001_021,Male 67 to 69 years
22,B01001,22.0,B01001_022,Male 70 to 74 years
23,B01001,23.0,B01001_023,Male 75 to 79 years
24,B01001,24.0,B01001_024,Male 80 to 84 years
25,B01001,25.0,B01001_025,Male 85 years and over
26,B01001,26.0,B01001_026,Total Female population
27,B01001,27.0,B01001_027,Female Under 5 years
28,B01001,28.0,B01001_028,Female 5 to 9 years
29,B01001,29.0,B01001_029,Female 10 to 14 years
...,...,...,...,...
131,B19001,14.0,B19001_014,"HOUSEHOLD INCOME between $100,000 to $124,999"
132,B19001,15.0,B19001_015,"HOUSEHOLD INCOME between $125,000 to $149,999"
133,B19001,16.0,B19001_016,"HOUSEHOLD INCOME between $150,000 to $199,999"
134,B19001,17.0,B19001_017,"HOUSEHOLD INCOME $200,000 or more"
135,B19013,1.0,B19013_001,Median household income in the past 12 months ...
136,B19101,1.0,B19101_001,Total:
137,B19101,2.0,B19101_002,"FAMILY INCOME Less than $10,000"
138,B19101,3.0,B19101_003,"FAMILY INCOME between $10,000 to $14,999"
139,B19101,4.0,B19101_004,"FAMILY INCOME between $15,000 to $19,999"
140,B19101,5.0,B19101_005,"FAMILY INCOME between $20,000 to $24,999"
141,B19101,6.0,B19101_006,"FAMILY INCOME between $25,000 to $29,999"
142,B19101,7.0,B19101_007,"FAMILY INCOME between $30,000 to $34,999"
143,B19101,8.0,B19101_008,"FAMILY INCOME between $35,000 to $39,999"
144,B19101,9.0,B19101_009,"FAMILY INCOME between $40,000 to $44,999"
145,B19101,10.0,B19101_010,"FAMILY INCOME between $45,000 to $49,999"
146,B19101,11.0,B19101_011,"FAMILY INCOME between $50,000 to $59,999"
147,B19101,12.0,B19101_012,"FAMILY INCOME between $60,000 to $74,999"
148,B19101,13.0,B19101_013,"FAMILY INCOME between $75,000 to $99,999"
149,B19101,14.0,B19101_014,"FAMILY INCOME between $100,000 to $124,999"
150,B19101,15.0,B19101_015,"FAMILY INCOME between $125,000 to $149,999"
151,B19101,16.0,B19101_016,"FAMILY INCOME between $150,000 to $199,999"
152,B19101,17.0,B19101_017,"FAMILY INCOME $200,000 or more"
153,B19113,1.0,B19113_001,Median family income in the past 12 months (in...
154,B19301,1.0,B19301_001,Per capita income in the past 12 months (in 20...
155,B25001,1.0,B25001_001,Total HOUSING UNITS
156,B25002,2.0,B25002_002,Occupied Housing units
157,B25002,3.0,B25002_003,Vacant Housing units
158,B25003,2.0,B25003_002,Tenure of Owner occupied housing units
159,B25003,3.0,B25003_003,Tenure of Renter occupied housing units
160,B25010,0.5,B25010_0.5,Average household size

In [6]:
acs_tables_key

,Table ID,Line,UniqueID,Stub
0,B00001,1.0,B00001_001,Total - UNWEIGHTED SAMPLE COUNT OF THE POPULA...
1,B00002,1.0,B00002_001,Total - UNWEIGHTED SAMPLE HOUSING UNITS
2,B01001,2.0,B01001_002,Total Male population
3,B01001,3.0,B01001_003,Male Under 5 years
4,B01001,4.0,B01001_004,Male 5 to 9 years
5,B01001,5.0,B01001_005,Male 10 to 14 years
6,B01001,6.0,B01001_006,Male 15 to 17 years
7,B01001,7.0,B01001_007,Male 18 and 19 years
8,B01001,8.0,B01001_008,Male 20 years
9,B01001,9.0,B01001_009,Male 21 years
10,B01001,10.0,B01001_010,Male 22 to 24 years
11,B01001,11.0,B01001_011,Male 25 to 29 years
12,B01001,12.0,B01001_012,Male 30 to 34 years
13,B01001,13.0,B01001_013,Male 35 to 39 years
14,B01001,14.0,B01001_014,Male 40 to 44 years
15,B01001,15.0,B01001_015,Male 45 to 49 years
16,B01001,16.0,B01001_016,Male 50 to 54 years
17,B01001,17.0,B01001_017,Male 55 to 59 years
18,B01001,18.0,B01001_018,Male 60 and 61 years
19,B01001,19.0,B01001_019,Male 62 to 64 years
20,B01001,20.0,B01001_020,Male 65 and 66 years
21,B01001,21.0,B01001_021,Male 67 to 69 years
22,B01001,22.0,B01001_022,Male 70 to 74 years
23,B01001,23.0,B01001_023,Male 75 to 79 years
24,B01001,24.0,B01001_024,Male 80 to 84 years
25,B01001,25.0,B01001_025,Male 85 years and over
26,B01001,26.0,B01001_026,Total Female population
27,B01001,27.0,B01001_027,Female Under 5 years
28,B01001,28.0,B01001_028,Female 5 to 9 years
29,B01001,29.0,B01001_029,Female 10 to 14 years
...,...,...,...,...
131,B19001,14.0,B19001_014,"HOUSEHOLD INCOME between $100,000 to $124,999"
132,B19001,15.0,B19001_015,"HOUSEHOLD INCOME between $125,000 to $149,999"
133,B19001,16.0,B19001_016,"HOUSEHOLD INCOME between $150,000 to $199,999"
134,B19001,17.0,B19001_017,"HOUSEHOLD INCOME $200,000 or more"
135,B19013,1.0,B19013_001,Median household income in the past 12 months ...
136,B19101,1.0,B19101_001,Total:
137,B19101,2.0,B19101_002,"FAMILY INCOME Less than $10,000"
138,B19101,3.0,B19101_003,"FAMILY INCOME between $10,000 to $14,999"
139,B19101,4.0,B19101_004,"FAMILY INCOME between $15,000 to $19,999"
140,B19101,5.0,B19101_005,"FAMILY INCOME between $20,000 to $24,999"
141,B19101,6.0,B19101_006,"FAMILY INCOME between $25,000 to $29,999"
142,B19101,7.0,B19101_007,"FAMILY INCOME between $30,000 to $34,999"
143,B19101,8.0,B19101_008,"FAMILY INCOME between $35,000 to $39,999"
144,B19101,9.0,B19101_009,"FAMILY INCOME between $40,000 to $44,999"
145,B19101,10.0,B19101_010,"FAMILY INCOME between $45,000 to $49,999"
146,B19101,11.0,B19101_011,"FAMILY INCOME between $50,000 to $59,999"
147,B19101,12.0,B19101_012,"FAMILY INCOME between $60,000 to $74,999"
148,B19101,13.0,B19101_013,"FAMILY INCOME between $75,000 to $99,999"
149,B19101,14.0,B19101_014,"FAMILY INCOME between $100,000 to $124,999"
150,B19101,15.0,B19101_015,"FAMILY INCOME between $125,000 to $149,999"
151,B19101,16.0,B19101_016,"FAMILY INCOME between $150,000 to $199,999"
152,B19101,17.0,B19101_017,"FAMILY INCOME $200,000 or more"
153,B19113,1.0,B19113_001,Median family income in the past 12 months (in...
154,B19301,1.0,B19301_001,Per capita income in the past 12 months (in 20...
155,B25001,1.0,B25001_001,Total HOUSING UNITS
156,B25002,2.0,B25002_002,Occupied Housing units
157,B25002,3.0,B25002_003,Vacant Housing units
158,B25003,2.0,B25003_002,Tenure of Owner occupied housing units
159,B25003,3.0,B25003_003,Tenure of Renter occupied housing units
160,B25010,0.5,B25010_0.5,Average household size

In [7]:
year=2017
variables_url = 'http://api.census.gov/data/'+str(year)+'/acs/acs5/variables.json'
data = requests.get(url=variables_url)
if data.status_code == 404:
    print('\bFailed')
    import sys
    sys.exit('You entered an invalid ACS year.  Please try again.')
else:
    data = data.json()
    print('\bDone')

Done

In [8]:
print('  Building table list...')
table_list = list() # This will hold all the tables.
acs_dict = dict() # This will hold the variables by table.
# Iterate through the variables
for variable in data['variables']:
    s = variable.split('_') # Break the string apart by the underscore.
    table = s[0] # This is the table name.
    
    if not table in table_list:
        table_list.append(table) # Add it to the table list
        var_list = list() # Create an empty list for the acs_dict
        var_list.append(variable) # Put the variable name in the list
        acs_dict[table] = var_list # Add the variable list to the dictionary
    else:
        var_list = acs_dict[table] # Pull the existing variable list
        var_list.append(variable) # Add in the new variable
        var_list.sort() # Sort it (so the estimates are followed by the MOE)
        acs_dict[table] = var_list # Replace the list with the updated one
print('\bDone')

  Building table list...
Done

In [9]:
required_table_list=acs_tables_key["Table\nID"]

In [10]:
acs_tables_key.columns

Index(['Table\nID', 'Line', 'UniqueID', 'Stub'], dtype='object')

In [11]:
required_table_list=list(numpy.unique(acs_tables_key["Table\nID"]))

In [12]:
required_variable_list=[]

In [12]:
os.getcwd()

"C:\\Users\\Umamounika.Karukonda\\OneDrive - Fractal Analytics Pvt. Ltd\\Documents\\Hill's\\US Vet Consulting\\Codes\\Demographic_2017"

In [13]:
os.chdir("C:\\Users\\Umamounika.Karukonda\\OneDrive - Fractal Analytics Pvt. Ltd\\Documents\\Hill's\\US Vet Consulting\\Codes\\Demographic_2017\\")

In [18]:
for table in required_table_list:
    if table in table_list:
        get_string=""
        for variable in list(acs_tables_key.ix[acs_tables_key["Table\nID"]==table,"UniqueID"]):
            if variable+"E" in acs_dict[table]:
                get_string+=","+variable+"E"
        if get_string=="":
            for variable in acs_dict[table]:
                get_string+=","+variable
        print(get_string)
        
        api_url = "http://api.census.gov/data/"+str(year)+"/acs/acs5?key="+api_key+"&get=NAME"+get_string+'&for=zip%20code%20tabulation%20area:*'
        table_data = pandas.io.json.read_json(api_url)
        colums_d=table_data.iloc[0,:]
        table_data=table_data.iloc[1:,1:]
        list_a=[]
        for i in colums_d[1:]:
            a=list(acs_tables_key.ix[acs_tables_key["UniqueID"]==i[:-1],"Stub"])
            if a !=[]:
                list_a.append(a)
        final_cols=list(itertools.chain(*list_a))
        final_cols.append('zip code tabulation area')
        table_data.columns=final_cols
        table_name=list(actual_acs_tables_key[actual_acs_tables_key["Table\nID"]==table]["Stub"])[0]
        table_data.to_csv(table_name[:128].replace("/","_")+".csv",index=False)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.

,B08302_001E,B08302_002E,B08302_003E,B08302_004E,B08302_005E,B08302_006E,B08302_007E,B08302_008E,B08302_009E,B08302_010E,B08302_011E,B08302_012E,B08302_013E,B08302_014E,B08302_015E

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.

,B08303_001E,B08303_002E,B08303_003E,B08303_004E,B08303_005E,B08303_006E,B08303_007E,B08303_008E,B08303_009E,B08303_010E,B08303_011E,B08303_012E,B08303_013E

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.

,B08602_001E,B08602_002E,B08602_003E,B08602_004E,B08602_005E,B08602_006E,B08602_007E,B08602_008E,B08602_009E,B08602_010E,B08602_011E,B08602_012E,B08602_013E,B08602_014E,B08602_015E

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.

,B17001_001E

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.

,B19001_001E,B19001_002E,B19001_003E,B19001_004E,B19001_005E,B19001_006E,B19001_007E,B19001_008E,B19001_009E,B19001_010E,B19001_011E,B19001_012E,B19001_013E,B19001_014E,B19001_015E,B19001_016E,B19001_017E

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.

,B19013_001E

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.

,B19101_001E,B19101_002E,B19101_003E,B19101_004E,B19101_005E,B19101_006E,B19101_007E,B19101_008E,B19101_009E,B19101_010E,B19101_011E,B19101_012E,B19101_013E,B19101_014E,B19101_015E,B19101_016E,B19101_017E

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.

,B19113_001E

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.

,B19301_001E

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.

,B25001_001E

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.

,B25002_002E,B25002_003E

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.

,B25003_002E,B25003_003E

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.

,B25010_001E,B25010_002E,B25010_003E

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

ValueError: Length mismatch: Expected axis has 4 elements, new values have 1 elements

In [22]:
for table in ['B25010','C11016']:
    get_string=""
    for variable in acs_dict[table][0:49]:
        get_string+=","+variable
    print(get_string)
    api_url = "http://api.census.gov/data/"+str(year)+"/acs/acs5?key="+api_key+"&get=NAME"+get_string+'&for=zip%20code%20tabulation%20area:*'
    table_data = pandas.io.json.read_json(api_url)
    colums_d=table_data.iloc[0,:]
    table_data=table_data.iloc[1:,1:]
    list_a=[]
    for i in colums_d[1:]:
        a=list(actual_acs_tables_key.ix[actual_acs_tables_key["UniqueID"]==i[:-1],"Stub"])
        if a !=[]:
            list_a.append(a)
    final_cols=list(itertools.chain(*list_a))
    final_cols.append('zip code tabulation area')
    table_data.columns=final_cols
    table_name=list(actual_acs_tables_key[actual_acs_tables_key["Table\nID"]==table]["Stub"])[0]
    table_data.to_csv(table_name[:128].replace("/","_")+".csv")

,B25010_001E,B25010_002E,B25010_003E

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  if sys.path[0] == '':

KeyError: 'C11016'

In [14]:
import os
files_req=os.listdir()
df1=pandas.read_csv(files_req[0])
for i in files_req[1:]:
    df2=pandas.read_csv(i)
    df1=df1.merge(df2,on="zip code tabulation area",how="inner")

In [15]:
df1

,Unnamed: 0,Total:_x,Owner occupied,Renter occupied,zip code tabulation area,Total:_y,"FAMILY INCOME Less than $10,000","FAMILY INCOME between $10,000 to $14,999","FAMILY INCOME between $15,000 to $19,999","FAMILY INCOME between $20,000 to $24,999",...,TRAVEL TIME TO WORK between 20 to 24 minutes,TRAVEL TIME TO WORK between 25 to 29 minutes,TRAVEL TIME TO WORK between 30 to 34 minutes,TRAVEL TIME TO WORK between 35 to 39 minutes,TRAVEL TIME TO WORK between 40 to 44 minutes,TRAVEL TIME TO WORK between 45 to 59 minutes,TRAVEL TIME TO WORK between 60 to 89 minutes,TRAVEL TIME TO WORK between 90 or more minutes,Total - UNWEIGHTED SAMPLE COUNT OF THE POPULATION,Total - UNWEIGHTED SAMPLE HOUSING UNITS
0,1,2.61,2.86,2.260000e+00,84306,119,0,0,0,0,...,41,31,21,0,0,9,0,0,20.0,NaN
1,2,2.21,2.18,2.530000e+00,84775,120,0,2,0,4,...,4,0,0,0,0,2,0,0,68.0,59.0
2,3,3.35,3.35,-6.666667e+08,84762,53,0,0,0,22,...,0,0,0,0,0,0,0,0,NaN,189.0
3,4,2.28,2.81,-6.666667e+08,84772,50,0,0,0,0,...,0,47,29,0,0,0,0,0,18.0,NaN
4,5,3.03,2.15,5.400000e+00,84781,52,0,0,0,0,...,0,0,0,17,0,0,0,0,15.0,31.0
5,6,3.39,3.25,3.930000e+00,84511,979,94,30,13,32,...,116,4,31,44,19,9,55,34,578.0,224.0
6,7,3.15,3.09,3.380000e+00,84513,392,8,21,16,5,...,19,9,68,33,30,49,0,3,252.0,99.0
7,8,2.76,2.54,5.800000e+00,84516,66,0,0,0,5,...,13,2,10,0,4,0,0,0,63.0,27.0
8,9,2.57,2.59,2.250000e+00,84522,105,2,0,8,7,...,6,2,19,11,3,15,17,0,146.0,69.0
9,10,2.46,2.51,2.320000e+00,84532,2702,202,69,148,101,...,167,15,150,40,88,114,11,141,567.0,321.0
10,11,3.13,3.50,2.840000e+00,84601,7963,376,250,418,577,...,2004,620,1189,160,248,556,413,333,3125.0,1004.0
11,12,2.94,2.94,2.940000e+00,84620,325,11,0,16,25,...,62,0,5,0,12,7,0,6,175.0,68.0
12,13,2.30,2.16,3.300000e+00,84628,150,0,0,10,6,...,16,13,16,12,21,14,40,12,138.0,69.0
13,14,3.07,2.86,4.360000e+00,84629,751,0,3,27,30,...,16,37,116,22,48,30,143,61,346.0,157.0
14,15,3.78,3.76,4.500000e+00,84630,115,0,0,4,0,...,0,1,3,6,0,0,7,2,96.0,35.0
15,16,3.10,3.03,3.550000e+00,84634,302,37,0,17,1,...,10,22,13,0,0,5,8,5,475.0,87.0
16,17,2.61,2.65,2.460000e+00,84647,1034,32,47,45,51,...,171,51,107,21,19,121,84,79,566.0,204.0
17,18,3.58,3.62,3.480000e+00,84663,7585,150,100,109,228,...,2328,858,1155,248,210,423,441,250,3659.0,1081.0
18,19,3.33,2.69,6.570000e+00,84710,26,0,1,0,4,...,2,5,3,0,0,2,11,2,62.0,42.0
19,20,3.87,3.96,3.350000e+00,84004,2474,43,6,20,46,...,228,366,562,263,204,297,160,62,1165.0,336.0
20,21,1.71,1.71,-6.666667e+08,84529,39,0,0,0,0,...,0,0,0,0,0,8,0,39,NaN,NaN
21,22,5.09,5.14,4.500000e+00,84531,152,26,9,21,19,...,29,0,26,0,37,23,13,10,203.0,91.0
22,23,4.57,4.65,4.090000e+00,84536,293,67,23,21,38,...,110,5,95,0,11,13,50,9,400.0,192.0
23,24,4.26,4.98,3.890000e+00,93249,440,19,12,27,43,...,260,49,57,0,0,39,25,9,359.0,96.0
24,25,2.66,2.39,3.070000e+00,93252,342,25,13,35,14,...,27,19,45,3,3,32,10,16,532.0,137.0
25,26,3.86,3.92,3.760000e+00,93270,1127,72,118,120,68,...,210,172,47,59,97,79,196,65,431.0,143.0
26,27,3.34,3.20,3.570000e+00,93291,13168,909,753,755,644,...,2281,943,1400,518,554,1344,783,285,2864.0,835.0
27,28,3.30,3.14,3.420000e+00,93304,10999,1078,780,747,779,...,3943,835,1984,90,437,970,556,396,3046.0,1051.0
28,29,3.20,3.15,3.300000e+00,93306,16497,876,615,950,645,...,5462,1568,2988,256,942,1149,1043,888,4703.0,1647.0
29,30,3.86,3.77,3.940000e+00,93307,18396,1526,1736,1132,1580,...,5525,2840,3902,437,693,1343,1393,480,4413.0,1356.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33090,33091,2.45,2.50,2.380000e+00,14904,3721,280,178,54,207,...,676,210,663,75,89,307,281,177,1112.0,498.0
33091,33092,2.86,2.87,2.700000e+00,14816,124,0,0,0,0,...,32,32,0,0,16,15,0,0,35.0,NaN
33092,33093,2.10,2.21,1.800000e+00,14750,1163,27,9,23,65,...,339,62,64,8,33,63,30,10,441.0,224.0
33093,33094,2.52,2.65,1.880000e+00,13108,1671,13,6,24,10,...,379,485,602,159,90,95,44,45,812.0,349.0
33094,33095,2.45,2.50,2.000000e+00,13072,166,6,0,9,11,...,27,23,53,10,25,37,40,0,207.0,122.0
33095,33096,2.70,3.01,2.040000e+00,13077,1907,34,45,63,34,...,408,153,373,84,258,293,26,35,806.0,359.0
33096,33097,2.33,2.32,2.370000e+00,14727,1434,46,46,50,39,...,298,165,219,108,35,161,64,64,1030.0,584.0
33097,33098,2.46,2.56,1.950000e+00,14747,629,16,23,22,48,...,224,77,129,40,14,56,9,11,431.0,187.0
33098,33099,2.89,2.47,3.860000e+00,14480,330,50,15,0,46,...,0,0,0,43,28,39,0,0,42.0,15.0
33099,33100,2.46,2.56,2.010000e+00,14487,1569,31,21,0,16,...,128,230,425,210,271,471,93,0,602.0,248.0
33100,33101,2.75,2.75,-6.666667e+08,14506,454,0,0,0,0,...,135,165,103,14,65,57,0,0,93.0,34.0
33101,33102,2.22,2.21,2.240000e+00,14536,147,1,10,1,5,...,21,19,29,8,19,31,15,13,239.0,109.0
33102,33103,2.51,2.59,1.980000e+00,14543,910,16,0,8,21,...,380,227,191,87,46,38,25,26,296.0,119.0
33103,33104,2.41,2.38,2.550000e+00,14548,1006,67,33,0,23,...,264,106,305,40,146,197,43,20,521.0,228.0
33104,33105,2.84,2.91,1.600000e+00,14568,1714,0,35,0,8,...,537,346,829,147,234,267,8,16,521.0,203.0
33105,33106,2.21,2.27,-6.666667e+08,14571,303,14,0,0,27,...,59,21,0,21,0,28,54,7,94.0,54.0
33106,33107,1.67,2.14,1.580000e+00,14607,1987,300,44,77,53,...,2159,456,758,74,175,249,345,34,1169.0,652.0
33107,33108,1.91,2.17,1.780000e+00,14620,3996,322,134,145,270,...,1908,547,597,45,48,246,183,146,2082.0,914.0
33108,33109,2.57,2.70,2.270000e+00,14715,769,67,31,46,29,...,167,88,295,38,42,29,34,34,693.0,322.0
33109,33110,2.44,2.50,2.260000e+00,14735,775,46,28,66,49,...,86,30,141,69,31,131,98,38,686.0,356.0
33110,33111,2.50,2.45,2.790000e+00,14741,545,6,26,12,25,...,187,32,107,8,40,38,47,20,388.0,216.0
33111,33112,2.25,2.29,2.100000e+00,14754,199,14,0,16,3,...,56,44,61,5,6,31,23,2,139.0,75.0
33112,33113,2.77,2.55,3.770000e+00,14783,97,16,10,1,10,...,25,9,33,11,0,2,0,0,104.0,55.0
33113,33114,2.37,2.19,3.210000e+00,14808,126,0,8,0,4,...,12,8,38,14,0,12,4,0,89.0,39.0
33114,33115,2.63,2.65,2.560000e+00,14801,1473,79,52,68,59,...,422,189,410,102,89,195,69,72,1252.0,521.0
33115,33116,2.07,2.09,1.940000e+00,14824,163,0,8,6,19,...,56,41,23,0,9,9,7,0,126.0,67.0
33116,33117,2.63,2.62,2.680000e+00,14839,198,5,0,2,4,...,40,24,26,8,8,23,28,5,223.0,118.0
33117,33118,2.03,2.09,1.760000e+00,14840,856,15,9,51,30,...,190,50,106,31,36,83,60,18,670.0,515.0
33118,33119,2.36,2.39,2.320000e+00,14843,3299,213,160,121,152,...,422,221,286,105,98,265,292,66,1737.0,763.0
33119,33120,2.31,2.44,1.860000e+00,14847,603,16,0,24,24,...,52,74,239,53,59,86,40,38,630.0,305.0

In [25]:
df1.to_csv("Demographic_details.csv",index=False)

In [27]:
len(final_cols)

49

In [28]:
table_data

,1,2,3,4,5,6,7,8,9,10,...,41,42,43,44,45,46,47,48,49,50
1,345,192,0,54,23,0,0,0,0,54,...,15,0,0,13,9,0,0,0,14,84306
2,421,188,13,0,8,10,5,0,3,0,...,18,0,38,6,10,26,26,12,0,84775
3,211,95,0,0,0,0,0,0,0,0,...,63,0,0,0,0,10,0,0,0,84762
4,203,103,0,0,15,9,0,0,0,29,...,0,0,0,6,0,13,10,26,0,84772
5,224,154,43,22,0,16,0,0,0,17,...,0,0,0,0,15,7,0,0,0,84781
6,4510,2277,136,212,321,217,67,18,59,133,...,108,88,94,54,87,36,56,17,64,84511
7,1649,799,59,124,89,43,8,0,0,9,...,46,24,45,14,13,20,10,11,17,84513
8,199,101,15,7,4,0,0,0,0,0,...,4,0,8,4,7,6,5,0,2,84516
9,364,214,13,22,19,8,3,0,5,4,...,13,15,7,5,6,3,2,13,4,84522
10,9968,4994,189,367,370,178,31,28,82,233,...,368,159,163,114,143,232,66,105,205,84532
11,34199,17752,1832,1582,1044,695,470,126,381,2649,...,655,214,321,79,200,212,167,154,126,84601
12,1024,489,23,19,65,28,6,0,0,3,...,50,29,22,32,19,15,6,37,16,84620
13,519,272,13,9,18,13,3,14,0,0,...,11,3,12,2,0,31,17,18,15,84628
14,2664,1149,94,61,97,124,17,5,30,15,...,109,31,10,38,65,83,46,54,22,84629
15,495,260,53,39,33,1,8,0,7,0,...,0,4,6,7,2,3,6,1,0,84630
16,3323,2757,38,57,93,36,120,12,25,175,...,12,19,6,20,10,9,10,0,14,84634
17,4299,2365,181,121,130,163,175,25,68,78,...,207,17,104,32,70,47,96,54,81,84647
18,32989,16539,1909,1917,1645,824,700,210,187,994,...,580,282,390,232,196,380,216,237,133,84663
19,143,66,8,2,2,7,0,0,0,0,...,0,0,0,0,4,7,0,6,0,84710
20,10256,5003,290,307,644,458,174,107,81,240,...,303,142,104,94,88,102,110,38,41,84004
21,245,109,0,0,0,0,0,0,0,0,...,0,19,37,0,0,33,0,0,9,84529
22,998,488,43,29,36,26,17,20,7,19,...,17,4,18,3,14,6,24,5,12,84531
23,1821,893,119,91,59,43,37,4,12,43,...,42,13,28,15,26,13,20,11,0,84536
24,2264,1180,149,107,111,71,37,32,16,128,...,30,7,4,0,0,0,10,0,0,93249
25,3188,2439,64,87,32,30,17,12,44,96,...,118,22,36,23,10,42,12,4,11,93252
26,5605,2868,130,267,271,165,96,3,60,176,...,123,41,110,36,44,62,23,39,21,93270
27,56627,27871,2474,2335,2948,1272,1205,463,312,1228,...,1437,567,681,399,633,567,405,374,309,93291
28,50787,25510,2581,2358,2116,1230,892,479,529,1255,...,1356,463,619,554,623,590,367,276,380,93304
29,70208,34741,3309,3492,3111,1416,1081,679,223,1448,...,1922,804,1042,749,728,1226,706,682,503,93306
30,84948,41271,3713,3876,4201,2226,1704,595,1009,1918,...,1820,785,1080,520,537,1055,372,496,319,93307
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33091,15861,7616,429,566,610,403,205,141,178,430,...,531,164,294,140,261,242,218,136,224,14904
33092,412,181,22,4,3,4,0,0,0,4,...,0,0,13,0,25,14,0,0,0,14816
33093,4373,1954,128,59,167,52,16,11,18,39,...,226,75,93,52,109,206,119,75,145,14750
33094,6139,3119,115,191,262,177,95,20,57,124,...,240,73,140,101,76,114,101,61,102,13108
33095,612,333,8,6,7,6,4,4,13,21,...,35,16,12,6,20,14,12,13,5,13072
33096,7074,3428,301,220,272,102,72,79,81,113,...,228,121,135,74,220,150,75,65,90,13077
33097,5114,2523,149,121,167,60,15,10,9,70,...,259,79,108,139,90,92,86,63,60,14727
33098,2268,1224,90,92,89,25,12,7,12,45,...,108,43,41,31,30,50,40,20,14,14747
33099,1049,460,44,0,50,43,0,0,3,0,...,0,46,0,0,14,80,0,0,12,14480
33100,5859,2765,118,208,183,108,80,50,24,206,...,156,89,131,44,87,133,64,42,116,14487
33101,1468,703,13,21,74,33,0,0,65,0,...,40,39,14,15,17,17,38,19,15,14506
33102,556,266,4,10,29,8,2,2,6,13,...,24,13,10,1,15,15,10,5,4,14536
33103,3285,1682,66,106,98,135,29,13,11,13,...,159,76,84,43,56,106,65,35,9,14543
33104,3791,1901,100,36,120,41,76,51,9,41,...,198,40,117,66,83,76,47,21,95,14548
33105,6009,3120,179,286,205,149,43,29,37,152,...,162,59,104,54,71,53,59,31,15,14568
33106,1061,545,28,47,9,15,24,0,5,28,...,50,34,40,29,23,40,52,0,0,14571
33107,16818,8690,181,99,233,110,147,84,152,947,...,366,147,258,73,184,192,140,102,154,14607
33108,24519,12375,611,301,529,139,492,211,233,1120,...,750,191,289,109,242,299,265,201,847,14620
33109,2913,1450,121,147,59,61,19,10,22,42,...,75,26,47,39,31,53,42,43,25,14715
33110,2879,1535,105,141,135,61,16,15,13,52,...,71,48,61,42,44,60,49,20,25,14735
33111,2081,1008,34,72,106,43,19,0,18,10,...,85,41,53,26,45,23,49,6,9,14741
33112,624,262,2,0,18,4,1,0,8,22,...,24,6,9,10,12,13,6,11,11,14754
33113,396,206,18,5,37,8,4,0,0,0,...,17,3,0,0,4,8,2,0,2,14783
33114,488,293,9,14,36,8,0,0,0,0,...,13,16,9,9,10,12,3,18,5,14808
33115,5529,2783,179,157,259,160,72,38,54,62,...,209,99,91,64,115,113,65,49,39,14801
33116,498,256,11,3,3,3,12,19,0,0,...,38,16,6,6,7,1,5,11,18,14824
33117,720,346,22,20,26,26,5,2,0,0,...,20,7,4,7,20,23,8,9,18,14839
33118,2829,1409,48,87,74,33,42,9,13,22,...,168,55,105,62,49,93,131,39,40,14840
33119,12919,6563,440,298,430,360,162,117,68,324,...,445,134,222,166,171,261,260,166,282,14843
33120,2372,1145,40,79,89,51,23,11,6,33,...,73,26,68,65,53,45,78,27,31,14847

In [30]:
get_string

',B01001_001E,B01001_002E,B01001_003E,B01001_004E,B01001_005E,B01001_006E,B01001_007E,B01001_008E,B01001_009E,B01001_010E,B01001_011E,B01001_012E,B01001_013E,B01001_014E,B01001_015E,B01001_016E,B01001_017E,B01001_018E,B01001_019E,B01001_020E,B01001_021E,B01001_022E,B01001_023E,B01001_024E,B01001_025E,B01001_026E,B01001_027E,B01001_028E,B01001_029E,B01001_030E,B01001_031E,B01001_032E,B01001_033E,B01001_034E,B01001_035E,B01001_036E,B01001_037E,B01001_038E,B01001_039E,B01001_040E,B01001_041E,B01001_042E,B01001_043E,B01001_044E,B01001_045E,B01001_046E,B01001_047E,B01001_048E,B01001_049E'

In [16]:
required_table_list=required_table_list[5:]

In [17]:
required_table_list

['B08302',
 'B08303',
 'B08602',
 'B17001',
 'B19001',
 'B19013',
 'B19101',
 'B19113',
 'B19301',
 'B25001',
 'B25002',
 'B25003',
 'B25010',
 'C11016']

In [17]:
a=pandas.read_csv("C:\\Users\\Umamounika.Karukonda\\OneDrive - Fractal Analytics Pvt. Ltd\\Documents\\Hill's\\US Vet Consulting\\Codes\\Demographic_details_33k_zipcodes.csv")

In [30]:
a.to_csv("\\\\falmumapp43\\Hills US Vet Channel Consulting (18-SCP-2568)\\Phase 2 - Suggested Order\\Demographics\\US Demographics\\Extracted from Census.gov\\Demographic_details_33kZipcodes.csv",index=False)

In [4]:
api_url="http://api.census.gov/data/2017/acs/acs5?key=605ccbb87ba11af806764361c2debc27dea1915a&get=NAME,B01001_001E&for=zip%20code%20tabulation%20area:*"

In [6]:
import pandas
table_data = pandas.io.json.read_json(api_url)

In [18]:
table_data=table_data.iloc[1:,1:]

In [20]:
table_data.columns=["Total population","zip code tabulation area"]

In [27]:
a=a.merge(table_data,on="zip code tabulation area",how="inner")

In [26]:
table_data["zip code tabulation area"]=table_data["zip code tabulation area"].astype('int64')

In [28]:
a

,zip code tabulation area,Total average household size of occupied household units,Owner occupied household size,Renter occupied household size,"FAMILY INCOME Less than $10,000","FAMILY INCOME between $10,000 to $14,999","FAMILY INCOME between $15,000 to $19,999","FAMILY INCOME between $20,000 to $24,999","FAMILY INCOME between $25,000 to $29,999","FAMILY INCOME between $30,000 to $34,999",...,TRAVEL TIME TO WORK between 25 to 29 minutes,TRAVEL TIME TO WORK between 30 to 34 minutes,TRAVEL TIME TO WORK between 35 to 39 minutes,TRAVEL TIME TO WORK between 40 to 44 minutes,TRAVEL TIME TO WORK between 45 to 59 minutes,TRAVEL TIME TO WORK between 60 to 89 minutes,TRAVEL TIME TO WORK between 90 or more minutes,Total - UNWEIGHTED SAMPLE COUNT OF THE POPULATION,Total - UNWEIGHTED SAMPLE HOUSING UNITS,Total population
0,84306,2.61,2.86,2.260000e+00,0,0,0,0,14,0,...,31,21,0,0,9,0,0,20.0,NaN,345
1,84775,2.21,2.18,2.530000e+00,0,2,0,4,40,3,...,0,0,0,0,2,0,0,68.0,59.0,421
2,84762,3.35,3.35,-6.666667e+08,0,0,0,22,0,0,...,0,0,0,0,0,0,0,NaN,189.0,211
3,84772,2.28,2.81,-6.666667e+08,0,0,0,0,0,14,...,47,29,0,0,0,0,0,18.0,NaN,203
4,84781,3.03,2.15,5.400000e+00,0,0,0,0,0,0,...,0,0,17,0,0,0,0,15.0,31.0,224
5,84511,3.39,3.25,3.930000e+00,94,30,13,32,57,38,...,4,31,44,19,9,55,34,578.0,224.0,4510
6,84513,3.15,3.09,3.380000e+00,8,21,16,5,15,31,...,9,68,33,30,49,0,3,252.0,99.0,1649
7,84516,2.76,2.54,5.800000e+00,0,0,0,5,7,0,...,2,10,0,4,0,0,0,63.0,27.0,199
8,84522,2.57,2.59,2.250000e+00,2,0,8,7,2,4,...,2,19,11,3,15,17,0,146.0,69.0,364
9,84532,2.46,2.51,2.320000e+00,202,69,148,101,116,81,...,15,150,40,88,114,11,141,567.0,321.0,9968
10,84601,3.13,3.50,2.840000e+00,376,250,418,577,571,580,...,620,1189,160,248,556,413,333,3125.0,1004.0,34199
11,84620,2.94,2.94,2.940000e+00,11,0,16,25,0,8,...,0,5,0,12,7,0,6,175.0,68.0,1024
12,84628,2.30,2.16,3.300000e+00,0,0,10,6,7,19,...,13,16,12,21,14,40,12,138.0,69.0,519
13,84629,3.07,2.86,4.360000e+00,0,3,27,30,7,17,...,37,116,22,48,30,143,61,346.0,157.0,2664
14,84630,3.78,3.76,4.500000e+00,0,0,4,0,1,11,...,1,3,6,0,0,7,2,96.0,35.0,495
15,84634,3.10,3.03,3.550000e+00,37,0,17,1,20,2,...,22,13,0,0,5,8,5,475.0,87.0,3323
16,84647,2.61,2.65,2.460000e+00,32,47,45,51,75,11,...,51,107,21,19,121,84,79,566.0,204.0,4299
17,84663,3.58,3.62,3.480000e+00,150,100,109,228,191,279,...,858,1155,248,210,423,441,250,3659.0,1081.0,32989
18,84710,3.33,2.69,6.570000e+00,0,1,0,4,1,1,...,5,3,0,0,2,11,2,62.0,42.0,143
19,84004,3.87,3.96,3.350000e+00,43,6,20,46,91,77,...,366,562,263,204,297,160,62,1165.0,336.0,10256
20,84529,1.71,1.71,-6.666667e+08,0,0,0,0,0,0,...,0,0,0,0,8,0,39,NaN,NaN,245
21,84531,5.09,5.14,4.500000e+00,26,9,21,19,10,7,...,0,26,0,37,23,13,10,203.0,91.0,998
22,84536,4.57,4.65,4.090000e+00,67,23,21,38,24,17,...,5,95,0,11,13,50,9,400.0,192.0,1821
23,93249,4.26,4.98,3.890000e+00,19,12,27,43,47,43,...,49,57,0,0,39,25,9,359.0,96.0,2264
24,93252,2.66,2.39,3.070000e+00,25,13,35,14,43,15,...,19,45,3,3,32,10,16,532.0,137.0,3188
25,93270,3.86,3.92,3.760000e+00,72,118,120,68,61,27,...,172,47,59,97,79,196,65,431.0,143.0,5605
26,93291,3.34,3.20,3.570000e+00,909,753,755,644,715,754,...,943,1400,518,554,1344,783,285,2864.0,835.0,56627
27,93304,3.30,3.14,3.420000e+00,1078,780,747,779,689,815,...,835,1984,90,437,970,556,396,3046.0,1051.0,50787
28,93306,3.20,3.15,3.300000e+00,876,615,950,645,805,1101,...,1568,2988,256,942,1149,1043,888,4703.0,1647.0,70208
29,93307,3.86,3.77,3.940000e+00,1526,1736,1132,1580,1390,1526,...,2840,3902,437,693,1343,1393,480,4413.0,1356.0,84948
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33090,14904,2.45,2.50,2.380000e+00,280,178,54,207,200,256,...,210,663,75,89,307,281,177,1112.0,498.0,15861
33091,14816,2.86,2.87,2.700000e+00,0,0,0,0,0,0,...,32,0,0,16,15,0,0,35.0,NaN,412
33092,14750,2.10,2.21,1.800000e+00,27,9,23,65,91,52,...,62,64,8,33,63,30,10,441.0,224.0,4373
33093,13108,2.52,2.65,1.880000e+00,13,6,24,10,29,50,...,485,602,159,90,95,44,45,812.0,349.0,6139
33094,13072,2.45,2.50,2.000000e+00,6,0,9,11,12,11,...,23,53,10,25,37,40,0,207.0,122.0,612
33095,13077,2.70,3.01,2.040000e+00,34,45,63,34,119,71,...,153,373,84,258,293,26,35,806.0,359.0,7074
33096,14727,2.33,2.32,2.370000e+00,46,46,50,39,44,78,...,165,219,108,35,161,64,64,1030.0,584.0,5114
33097,14747,2.46,2.56,1.950000e+00,16,23,22,48,22,24,...,77,129,40,14,56,9,11,431.0,187.0,2268
33098,14480,2.89,2.47,3.860000e+00,50,15,0,46,0,23,...,0,0,43,28,39,0,0,42.0,15.0,1049
33099,14487,2.46,2.56,2.010000e+00,31,21,0,16,130,13,...,230,425,210,271,471,93,0,602.0,248.0,5859
33100,14506,2.75,2.75,-6.666667e+08,0,0,0,0,0,0,...,165,103,14,65,57,0,0,93.0,34.0,1468
33101,14536,2.22,2.21,2.240000e+00,1,10,1,5,7,12,...,19,29,8,19,31,15,13,239.0,109.0,556
33102,14543,2.51,2.59,1.980000e+00,16,0,8,21,13,49,...,227,191,87,46,38,25,26,296.0,119.0,3285
33103,14548,2.41,2.38,2.550000e+00,67,33,0,23,11,45,...,106,305,40,146,197,43,20,521.0,228.0,3791
33104,14568,2.84,2.91,1.600000e+00,0,35,0,8,26,104,...,346,829,147,234,267,8,16,521.0,203.0,6009
33105,14571,2.21,2.27,-6.666667e+08,14,0,0,27,19,20,...,21,0,21,0,28,54,7,94.0,54.0,1061
33106,14607,1.67,2.14,1.580000e+00,300,44,77,53,52,112,...,456,758,74,175,249,345,34,1169.0,652.0,16818
33107,14620,1.91,2.17,1.780000e+00,322,134,145,270,210,244,...,547,597,45,48,246,183,146,2082.0,914.0,24519
33108,14715,2.57,2.70,2.270000e+00,67,31,46,29,36,58,...,88,295,38,42,29,34,34,693.0,322.0,2913
33109,14735,2.44,2.50,2.260000e+00,46,28,66,49,56,73,...,30,141,69,31,131,98,38,686.0,356.0,2879
33110,14741,2.50,2.45,2.790000e+00,6,26,12,25,10,34,...,32,107,8,40,38,47,20,388.0,216.0,2081
33111,14754,2.25,2.29,2.100000e+00,14,0,16,3,8,0,...,44,61,5,6,31,23,2,139.0,75.0,624
33112,14783,2.77,2.55,3.770000e+00,16,10,1,10,0,5,...,9,33,11,0,2,0,0,104.0,55.0,396
33113,14808,2.37,2.19,3.210000e+00,0,8,0,4,0,5,...,8,38,14,0,12,4,0,89.0,39.0,488
33114,14801,2.63,2.65,2.560000e+00,79,52,68,59,73,79,...,189,410,102,89,195,69,72,1252.0,521.0,5529
33115,14824,2.07,2.09,1.940000e+00,0,8,6,19,2,12,...,41,23,0,9,9,7,0,126.0,67.0,498
33116,14839,2.63,2.62,2.680000e+00,5,0,2,4,32,4,...,24,26,8,8,23,28,5,223.0,118.0,720
33117,14840,2.03,2.09,1.760000e+00,15,9,51,30,25,14,...,50,106,31,36,83,60,18,670.0,515.0,2829
33118,14843,2.36,2.39,2.320000e+00,213,160,121,152,211,147,...,221,286,105,98,265,292,66,1737.0,763.0,12919
33119,14847,2.31,2.44,1.860000e+00,16,0,24,24,31,26,...,74,239,53,59,86,40,38,630.0,305.0,2372